### ISSUE TITLE
Controlling sims on an apartment zone causes exceptions

### ISSUE THREAD

**Issue by TitanNano** [TitanNano/TS4ControlAnySim#30]
Trying to control sims on an apartment zone can cause exceptions. The apartment aspirations feature tries to access a sims' aspiration tracker which appears to not always exist.

```
running make selectable interaction...
got sim info Caleb Vatore
Traceback (most recent call last):
  File "src/control_any_sim/interactions.py", line 72, in _run_interaction_gen
  File "src/control_any_sim/services/selection_group.py", line 124, in make_sim_selectable
  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 374, in add_selectable_sim_info
  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 1006, in add_selectable_sim_info
  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 469, in on_sim_added_to_skewer
  File "T:\InGame\Gameplay\Scripts\Server\apartments\apartment_zone_director.py", line 197, in on_sim_added_to_skewer
  File "T:\InGame\Gameplay\Scripts\Server\apartments\apartment_zone_director.py", line 214, in _register_zone_aspriations_for_sim
AttributeError: 'NoneType' object has no attribute 'reset_milestone'
```

**Comment by TitanNano** [comment]
Has been verified as fixed.
